name: terraform-plan

on:
  pull_request:
    paths:
      - "infra/terraform/**"
      - ".github/workflows/terraform-plan.yml"

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  preview-plan:
    runs-on: ubuntu-latest
    env:
      TF_VAR_container_image: 000000000000.dkr.ecr.us-east-1.amazonaws.com/brokerops-api:preview-plan
      TF_VAR_database_password: preview-plan-only-password
    defaults:
      run:
        working-directory: infra/terraform/environments/preview

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        if: ${{ secrets.AWS_ROLE_ARN != '' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION || 'us-east-1' }}

      - run: terraform fmt -check -recursive ../..
      - run: terraform init
      - run: terraform validate
      - run: terraform plan -out preview.tfplan
